workflows:
  ios-swiftui-build:
    name: Build Swift Store IPA
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "Ksign.xcworkspace"
        XCODE_SCHEME: "Ksign"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up build directory
        script: | 
          mkdir -p build/Release-iphoneos
      - name: Build IPA
        script: | 
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -archivePath build/Ksign.xcarchive \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Export Unsigned IPA
        script: |
          cd build/Ksign.xcarchive/Products/Applications/ || exit 1
          mkdir -p Payload
          cp -r *.app Payload/
          zip -r SwiftStore.ipa Payload
          mv SwiftStore.ipa $CM_BUILD_DIR/
    artifacts:
      - "*.ipa"
